### ISSUE TITLE
Could not start application gmail

### ISSUE THREAD

**Issue by ponty96** [craigp/elixir-gmail#11]
I'm getting this after adding `gmail` to my `mix.exs` in a phoenix app

```
** (Mix) Could not start application gmail: Gmail.start(:normal, []) returned an error: shutdown: failed to start child: Gmail.Thread.Pool
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Keyword.get/3
            (elixir) lib/keyword.ex:150: Keyword.get(nil, :pool, nil)
            (gmail) lib/gmail/thread/pool.ex:48: Gmail.Thread.Pool.pool_size/0
            (gmail) lib/gmail/thread/pool.ex:18: Gmail.Thread.Pool.start_link/0
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by craigp** [comment]
Add this to your config:

```elixir
config :gmail, :thread,
  pool: 100

config :gmail, :message,
  pool: 100
```

It really shouldn't crash though, I'll fix that in the next version.

**Comment by ponty96** [comment]
okay it works now... thanks

**Comment by craigp** [comment]
This was fixed in https://github.com/craigp/elixir-gmail/commit/21f18e5405d81394b22ce24fe33249c9e9a108b5
